### ISSUE TITLE
[Help] Some problems about customizing my own dataset for training/testing GCA model

### ISSUE THREAD

**Issue by Karbo123** [96lives/gca#1]
I really appreciate this interesting work, which nicely bridges up two seemingly different areas. I'm currently interested in applying the GCA (not cGCA) model to a new dataset (actually, it's ShapeNet with more categories). It would be great if you can give me some help regarding how to custom a new dataset. I've tried to read the source codes of `TransitionShapenetDataset`, but I still feel a bit confused.
![image](https://user-images.githubusercontent.com/42935526/170052619-b7075f94-501c-4ba8-bd8d-0fbfcff2f482.png)
It seems that the dataset requires embeddings to train the GCA model, and the read context is then used to output `embedding_coord`, `embedding_feat`, `input_pc`, `state_coord`, respectively. **What are the default values for `embedding['coord']`, `embedding['feat']` and `embedding['translation']`?** I think it's important because in the training script, it takes the embedding information as input, and therefore we have to give them some default values.

Besides, I think the current released version may still have some room for small improvements, including but not limited to, the actual dataset folder is named `cgca_shapenet` rather than `shapenet_sdf`; config file `configs/gca-shapenet-vox=64.yaml` provides a None value for the `embedding_root:` key, which certainly causes problem when trying to compute the `self.embedding_root` for `TransitionShapenetDataset`.

Many thanks!!

**Comment by 96lives** [comment]
Thank you for your interest! 

The confusion might be coming from GCA using the same dataset as cGCA. The `embedding['coord']` is a tensor of N x 3, having coordinate values of points of the surface, with N being the number of coordinates. `embedding['feat']` is a tensor of N x 32, with N being the number of coordinates and 32 is the dimension of features z for cGCA. `embedding['translation'][:, :3]` is the random translation used for data augmentation having with the tensor of shape N x 3. The translation data augmentation is useful in cGCA, because even a small translation in the point coordinate might change the local features a lot. Although for GCA, I don't think it will require the translation data augmentation, if the voxel resolution is high enough.

Regarding the features of GCA, we just use features of 1, so for the input with N x 3 coordinates size, the output of the DataLoader `__getitem__()` should have dictionary values of N x 1 tensor (with all having values of 1) for key `state_feat`. Instead of using the if statement, which I have to modify for all the datasets repeatedly, I use a python decorator `change_feat()` defined in [link](https://github.com/96lives/gca/blob/8571c4a54ef95d5192842dc0970d57c01516858b/datasets/transition_dataset.py#L29), which can be applied to all the datasets easily. 

The best way to check this is to download the [preprocessed dataset](https://drive.google.com/drive/folders/15G_rGfVlTRL5QyZ3_vGU4hWtEg0497Ty), and create a breakpoint in `learn()` (https://github.com/96lives/gca/blob/8571c4a54ef95d5192842dc0970d57c01516858b/models/gca.py#L63), and check the values that are used there. 

For the config values of the `embedding_root`, I should change like as you said, soon. Thanks for the comments

**Comment by Karbo123** [comment]
Very appreciate for the detailed reply! May I have another question?
I also found that the following codes try to generate random sampled points that are within ball radius `self.sphere_radius` from center points `sphere_centers`, I would recommand using [pytorch_cluster](https://github.com/rusty1s/pytorch_cluster#radius-graph) for speedup.
https://github.com/96lives/gca/blob/8571c4a54ef95d5192842dc0970d57c01516858b/datasets/transition_dataset.py#L229-L239
And it seems that the above codes are only for training a cGCA model (if we want to complete a point cloud), not for training a GCA model? If we want to change the dataset to train a GCA model, maybe we should remove the above codes and rewrite the codes which produces `point_coord` that is the partially observed point cloud, not the uniformly ball-query downsampled one?

**Comment by 96lives** [comment]
I don't think there's a bottleneck in creating the partial pointcloud. 

If you see [below](https://github.com/96lives/gca/blob/8571c4a54ef95d5192842dc0970d57c01516858b/datasets/transition_dataset.py#L254), there is a quantizing function after the removal. The code will work properly with GCA as well. Also, much of papers assume that point cloud is the input, not the voxel. Although GCA uses sparse voxels for input, for a fair comparison, it is best that we process point cloud first and convert that to sparse voxels

**Comment by Karbo123** [comment]
Yeah, I got your point that point cloud do need to be voxelized.
Since I'm interested in the completion task, and therefore wonder if for GCA's input, If I understand correctly, during training stage, it should be a partially observed cloud (shown below at the right) instead of the randomly picked one (shown below at the middle)?
![image](https://user-images.githubusercontent.com/42935526/170190707-13088031-3da6-4ab1-827f-4b06a231815f.png)
It seems that the current codes only implement the middle case, which is for cGCA only. So do I understand correctly, and need to change the codes to the right case? Or the GCA is able to train on the middle case, but generalize to the right case during inference?

**Comment by Karbo123** [comment]
Thanks very much!!
I think I've totally understood the shape and dtype, and I post the resuts here to help anybody who wants to build their own dataset. Everybody can visualize them by exporting to point cloud files.
```
input_pc ==> (1024, 3)             ==> partially observed pc (cropped by ball query)
state_coord ==> (678, 3)                          ==> after quantized     int32,    voxelized partially observed voxel
state_feat ==> (678, 1) ==> all ones       ==> after quantized
embedding_coord ==> (5642, 3)  ==> int32, max(30), min(-27)  ==> complete voxel (served as GT)
embedding_feat ==> (5642, 32) 
```
And I may also think that the bottleneck problem may not happen, because in this case, `self.max_sphere_centers` is set to `1`, and `self.sphere_radius` is 0.5, which means the python for loop will only run once. This also implies that the cropped point cloud will have a ball-shaped boundary. 
And notice that the illustration posted [here](https://github.com/96lives/gca/issues/1#issuecomment-1136766408) is actually wrong. It may more like this:
![image](https://user-images.githubusercontent.com/42935526/170218345-29c84e42-f120-46cc-941c-f8a6712586c7.png)
